# Generated by Django 3.1.4 on 2020-12-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20201210_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_toppings',
            field=models.CharField(blank=True, choices=[('Onion', 'Onion'), ('Tomato', 'Tomato'), ('Corn', 'Corn'), ('Capsicum', 'Capsicum'), ('Cheese', 'Cheese'), ('Jalapeno', 'Jalapeno')], max_length=50, null=True),
        ),
    ]
